server:
  port: 0

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalog-dev
      username: usr-catalog
      password: pwd-catalog

sleuth:
  sampler:
    probability: 1.0

rabbitmq:
  addresses: localhost:5672
  virtual-host: app_vhost
  username: username
  password: password

zipkin:
  baseUrl: http://localhost:9411/
  enabled: true
  sender:
    type: rabbit
  enabled: true

application:
  name: catalog-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
