server:
  port: 0
spring:
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    username: guest
    password: guest
    host: localhost 
    port: 5672
  zipkin:
    baseUrl: http://zipkin:9411/ 
    enabled: true
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://eureka-server:8761/eureka

queue:
  serie:
    name: serieQueue
